import os
import io
import uuid
import structlog
from typing import List, Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from datetime import datetime

logger = structlog.get_logger(__name__)

class PDFGenerator:
    """Generates downloadable health summary PDFs."""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.title_style = self.styles['Heading1']
        self.heading_style = self.styles['Heading2']
        self.normal_style = self.styles['Normal']
        
    def generate_health_summary(self, patient_profile: Any, insights: List[Any], trends: Dict[str, Any]) -> bytes:
        logger.info("Generating PDF summary")
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
        
        elements = []
        
        # Title
        elements.append(Paragraph(f"Health Intelligence Summary", self.title_style))
        elements.append(Paragraph(f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}", self.normal_style))
        elements.append(Spacer(1, 20))
        
        # Profile Info
        elements.append(Paragraph("Patient Profile", self.heading_style))
        elements.append(Paragraph(f"Name: {patient_profile.name}", self.normal_style))
        elements.append(Paragraph(f"Age: {patient_profile.age} | Gender: {patient_profile.gender}", self.normal_style))
        if patient_profile.allergies:
            elements.append(Paragraph(f"Allergies: {patient_profile.allergies}", self.normal_style))
        if patient_profile.chronic_conditions:
            elements.append(Paragraph(f"Chronic Conditions: {patient_profile.chronic_conditions}", self.normal_style))
        elements.append(Spacer(1, 20))
        
        # Insights
        elements.append(Paragraph("Key Health Insights", self.heading_style))
        if not insights:
            elements.append(Paragraph("No recent insights available.", self.normal_style))
        else:
            for ins in insights:
                # Format: [Category] Title - Description
                text = f"<b>[{ins.category}] {ins.title}</b><br/>{ins.description}"
                elements.append(Paragraph(text, self.normal_style))
                elements.append(Spacer(1, 10))
        elements.append(Spacer(1, 20))
        
        # Trends
        elements.append(Paragraph("Laboratory Trends", self.heading_style))
        trend_data = trends.get("trends", {})
        if not trend_data:
            elements.append(Paragraph("No trend data available.", self.normal_style))
        else:
            # Create a table for trends
            table_data = [["Parameter", "Direction", "Change %"]]
            for param, data in trend_data.items():
                table_data.append([param, data['overall_direction'], f"{data['pct_change']}%"])
                
            t = Table(table_data, colWidths=[200, 100, 100])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0f766e')),
                ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
                ('ALIGN', (0,0), (-1,-1), 'CENTER'),
                ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0,0), (-1,0), 12),
                ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#f8fafc')),
                ('GRID', (0,0), (-1,-1), 1, colors.HexColor('#cbd5e1'))
            ]))
            elements.append(t)
            
        elements.append(Spacer(1, 30))
        elements.append(Paragraph("<i>Disclaimer: This document is generated by an AI and does not constitute medical advice. Always consult your physician.</i>", self.normal_style))

        # Build PDF
        doc.build(elements)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes

pdf_generator = PDFGenerator()
